animals = {'flamingo': '$fla', 'worm': '$wor', 'cormorant': '$cor', 'crow': '$cro', 'kingfisher': '$kin',
          'chimpanzee': '$chi', 'chamois': '$cha', 'elk': '$elk', 'squid': '$squ', 'clam': '$cla', 'gnu': '$gnu',
          'bear': '$bea', 'jellyfish': '$jel', 'otter': '$ott', 'rat': '$rat', 'albatross': '$alb', 'kangaroo': '$kan',
          'caribou': '$car', 'mantis': '$man', 'bee': '$bee', 'cat': '$cat', 'gerbil': '$ger', 'human': '$hum',
          'dragonfly': '$dra', 'crocodile': '$cro', 'woodpecker': '$woo', 'crab': '$cra', 'monkey': '$mon',
          'cheetah': '$che', 'deer': '$dee', 'dogfish': '$dog', 'pigeon': '$pig', 'chough': '$cho', 'jackal': '$jac',
          'ape': '$ape', 'sheep': '$she', 'coyote': '$coy', 'aardvark': '$aar', 'guanaco': '$gua', 'owl': '$owl',
          'curlew': '$cur', 'oryx': '$ory', 'boar': '$boa', 'goshawk': '$gos', 'squirrel': '$squ', 'fish': '$fis',
          'spoonbill': '$spo', 'giraffe': '$gir', 'beaver': '$bea', 'alpaca': '$alp', 'hedgehog': '$hed',
          'tarsier': '$tar', 'goldfinch': '$gol', 'echidna': '$ech', 'stingray': '$sti', 'goose': '$goo',
          'donkey': '$don', 'armadillo': '$arm', 'pig': '$pig', 'meerkat': '$mee', 'swan': '$swa', 'mole': '$mol',
          'quetzal': '$que', 'cod': '$cod', 'turtle': '$tur', 'bat': '$bat', 'dolphin': '$dol', 'vulture': '$vul',
          'skunk': '$sku', 'ram': '$ram', 'chinchilla': '$chi', 'lyrebird': '$lyr', 'fox': '$fox', 'loris': '$lor',
          'hummingbird': '$hum', 'leopard': '$leo', 'eland': '$ela', 'butterfly': '$but', 'stork': '$sto',
          'wren': '$wre', 'cassowary': '$cas', 'hyena': '$hye', 'gaur': '$gau', 'raccoon': '$rac', 'eagle': '$eag',
          'duck': '$duc', 'llama': '$lla', 'heron': '$her', 'kouprey': '$kou', 'mosquito': '$mos', 'reddeer': '$red',
          'quail': '$qua', 'anteater': '$ant', 'frog': '$fro', 'rhinoceros': '$rhi', 'trout': '$tro', 'goat': '$goa',
          'emu': '$emu', 'octopus': '$oct', 'gnat': '$gna', 'peafowl': '$pea', 'bison': '$bis', 'hippopotamus': '$hip',
          'manatee': '$man', 'cockroach': '$coc', 'panther': '$pan', 'porpoise': '$por', 'mouse': '$mou',
          'buffalo': '$buf', 'elephant': '$ele', 'dinosaur': '$din', 'gull': '$gul', 'tiger': '$tig', 'viper': '$vip',
          'porcupine': '$por', 'wildebeest': '$wil', 'lapwing': '$lap', 'wasp': '$was', 'eel': '$eel',
          'gazelle': '$gaz', 'sandpiper': '$san', 'chicken': '$chi', 'turkey': '$tur', 'wolf': '$wol', 'koala': '$koa',
          'walrus': '$wal', 'okapi': '$oka', 'ostrich': '$ost', 'quelea': '$que', 'rail': '$rai', 'hornet': '$hor',
          'tapi': '$tap', 'dove': '$dov', 'shrew': '$shr', 'wombat': '$wom', 'sardine': '$sar', 'badger': '$bad',
          'caterpillar': '$cat', 'stinkbug': '$sti', 'raven': '$rav', 'scorpion': '$sco', 'penguin': '$pen',
          'lion': '$lio', 'jay': '$jay', 'locust': '$loc', 'antelope': '$ant', 'barracuda': '$bar', 'wallaby': '$wal',
          'horse': '$hor', 'salamander': '$sal', 'baboon': '$bab', 'camel': '$cam', 'zebra': '$zeb', 'pheasant': '$phe',
          'hare': '$har', 'magpie': '$mag', 'opossum': '$opo', 'snail': '$sna', 'lemur': '$lem', 'narwhal': '$nar',
          'ferret': '$fer', 'mink': '$min', 'moose': '$moo', 'starling': '$sta', 'spider': '$spi', 'rook': '$roo',
          'cobra': '$cob', 'pelican': '$pel', 'mongoose': '$mon', 'crane': '$cra', 'lark': '$lar',
          'nightingale': '$nig', 'louse': '$lou', 'wildcat': '$wil', 'rabbit': '$rab', 'termite': '$ter',
          'alligator': '$all', 'dog': '$dog', 'tapir': '$tap', 'mallard': '$mal', 'jaguar': '$jag', 'mandrill': '$man',
          'hawk': '$haw', 'finch': '$fin', 'capybara': '$cap', 'newt': '$new', 'cattle': '$cat', 'ibex': '$ibe',
          'woodcock': '$woo', 'hamster': '$ham', 'partridge': '$par', 'kookaburra': '$koo', 'oyster': '$oys',
          'snake': '$sna', 'herring': '$her', 'seahorse': '$sea', 'gorilla': '$gor', 'seal': '$sea', 'whale': '$wha',
          'marten': '$mar', 'sanddollar': '$san', 'falcon': '$fal', 'toad': '$toa', 'kudu': '$kud', 'ox': '$ox',
          'grasshopper': '$gra', 'pony': '$pon', 'mule': '$mul', 'ant': '$ant', 'grouse': '$gro', 'dugong': '$dug',
          'ibis': '$ibi', 'yak': '$yak', 'swallow': '$swa', 'goldfish': '$gol', 'parrot': '$par', 'salmon': '$sal',
          'dunlin': '$dun', 'fly': '$fly', 'shark': '$sha', 'dotterel': '$dot', 'redpanda': '$red', 'reindeer': '$rei',
          'vicuna': '$vic', 'sparrow': '$spa', 'lobster': '$lob', 'weasel': '$wea'}
